#!/usr/bin/env python3
"""Emit rom/data.inc -- the operand arrays and the quarter-square tables.

Everything is deterministic (fixed seed) so the host can predict, byte for
byte, what each primitive on the console should compute.  That prediction is
the correctness check: a primitive that is fast because it is broken gets
caught here and not in the cycles table.

Arrays are 128 elements so that a page-aligned 16-bit array is 256 bytes and
`abs,y` indexing can never cross a page -- absolute-indexed reads on the 65816
cost one extra cycle when they do, and a variable cost would smear every
measurement.
"""
import random
import sys

N = 128

random.seed(0x5A17)
WB = [random.randrange(256) for _ in range(N)]        # weights, uint8
XB = [random.randrange(256) for _ in range(N)]        # activations, uint8
PERM = list(range(N))
random.shuffle(PERM)                                   # ternary gather indices


def s8(v: int) -> int:
    return v - 256 if v > 127 else v


def rows(name, words, per=8):
    out = [f"{name}:"]
    for i in range(0, len(words), per):
        chunk = ", ".join(f"${w:04X}" for w in words[i:i + per])
        out.append(f"        .word {chunk}")
    return out


def brows(name, bytes_, per=16):
    out = [f"{name}:"]
    for i in range(0, len(bytes_), per):
        chunk = ", ".join(f"${b:02X}" for b in bytes_[i:i + per])
        out.append(f"        .byte {chunk}")
    return out


def main(path):
    L = []
    L.append("; GENERATED by tools/gendata.py -- do not edit")
    L.append("        .segment \"RODATA\"")
    L.append("")

    # --- 8-bit operand arrays ------------------------------------------------
    L.append("        .align 256")
    L += brows("WB", WB)
    L.append("        .align 256")
    L += brows("XB", XB)

    # --- 16-bit forms --------------------------------------------------------
    # zero-extended, for the quarter-square path
    L.append("        .align 256")
    L += rows("W16Z", WB)
    L.append("        .align 256")
    L += rows("X16Z", XB)

    # PPU Mode 7: WHI holds w<<8 so that `stx $211A` lands w in $211B (M7A low
    # byte).  XHI holds x<<8 so that `stx $211B` lands 0 in $211B (M7A high
    # byte) and x in $211C (M7B).  Two 16-bit stores, three register writes.
    L.append("        .align 256")
    L += rows("WHI", [(w << 8) & 0xFFFF for w in WB])
    L.append("        .align 256")
    L += rows("XHI", [(x << 8) & 0xFFFF for x in XB])

    # CPU multiplier, pre-packed: low byte -> $4202 (A), high byte -> $4203 (B),
    # so one 16-bit store loads both operands and starts the multiply.
    L.append("        .align 256")
    L += rows("PK", [((x << 8) | w) & 0xFFFF for w, x in zip(WB, XB)])

    # ternary gather: pre-doubled indices into a 16-bit activation array
    L.append("        .align 256")
    L += rows("IDX", [2 * p for p in PERM])
    L.append("        .align 256")
    L += rows("XS16", [(s8(x) - 0) & 0xFFFF for x in XB])

    # --- quarter-square tables ----------------------------------------------
    # a*b = QS1[a+b] - QS2[(a-b)+255], exact for 0 <= a,b <= 255.
    L.append("        .align 256")
    L += rows("QS1", [(n * n) >> 2 for n in range(511)])
    L.append("        .align 256")
    L += rows("QS2", [((n - 255) * (n - 255)) >> 2 for n in range(511)])

    open(path, "w").write("\n".join(L) + "\n")

    # --- the predictions -----------------------------------------------------
    m16 = lambda v: v & 0xFFFF
    exp = {}
    exp["unsigned_mul"] = m16(sum(w * x for w, x in zip(WB, XB)))
    exp["signed_ppu"] = m16(sum(w * s8(x) for w, x in zip(WB, XB)))
    tern = 0
    for i in range(N):
        v = s8(XB[PERM[i]])
        tern += v if (i % 16) < 8 else -v
    exp["ternary"] = m16(tern)

    print(f"gendata: wrote {path}")
    for k, v in exp.items():
        print(f"  expect {k:14s} = ${v:04X} ({v})")
    return exp


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "rom/data.inc")
