#!/usr/bin/env python3
"""Emit rom/kern.inc -- operand data and the four ternary gather kernels whose
inner loops are being compared, plus the host predictions that prove each one
computed the right sum.

The question this data answers is the one the brief asks: the NES port found
that 8-bit register residency was the whole driver of its inner-loop cost, and
the 65816 has a 16-bit accumulator in native mode.  Does that finding survive?

Four shapes are emitted, all summing the same 128 biased activations through
the same permutation, so a wrong one is caught by its sum and not by its
cycles:

  i16abs   ldx IDXW,y / adc ACT16,x      16-bit index regs, absolute activations
  i16dp    ldx IDXW,y / adc <ACT,x       16-bit index regs, direct-page activations
  i8dp16   ldx IDXB2,y / adc <ACT,x       8-bit index regs, 16-bit accumulator
  i8acc    ldx IDXB1,y / adc <ACT8,x      8-bit index regs,  8-bit accumulator
                                          + one 16-bit fold every 16 elements
  code     adc <ACT+2i                   the index baked into the operand field
  code8    adc <ACT8+i (8-bit) + folds    the same, 8-bit accumulator

`code` is the shape the SNES makes possible and the NES did not: the weights
are static, the machine has a 24-bit address space and megabytes of ROM, so the
gather index can live in the instruction's own operand byte and the load that
fetches it disappears.

Activations are stored BIASED (value + 7, so 0..14) exactly as the NES port
stores them, which is what lets a run of `adc` need no `clc` between elements.
"""
import random
import sys

N = 128
BIAS = 7

random.seed(0x5A17)
PERM = list(range(N))
random.shuffle(PERM)
ACT = [random.randrange(15) for _ in range(N)]      # biased already: 0..14

# The sign-separated form the engine actually emits: one run of `adc` for the
# +1 list, one `sec`, one run of `sbc` for the -1 list.  START keeps the
# accumulator positive throughout so no adc carries out and no sbc borrows.
START = 4096


def brows(name, vals, per=16):
    out = [f"{name}:"]
    for i in range(0, len(vals), per):
        out.append("        .byte " + ", ".join(f"${v:02X}" for v in vals[i:i + per]))
    return out


def wrows(name, vals, per=8):
    out = [f"{name}:"]
    for i in range(0, len(vals), per):
        out.append("        .word " + ", ".join(f"${v:04X}" for v in vals[i:i + per]))
    return out


def main(path):
    L = ["; GENERATED by tools/genkern.py -- do not edit", ""]

    L.append('        .segment "RODATA"')
    L.append("        .align 256")
    L += wrows("IDXW", [2 * p for p in PERM])          # 16-bit index regs
    L.append("        .align 256")
    L += brows("IDXB2", [2 * p for p in PERM])         # 8-bit regs -> 16-bit array
    L.append("        .align 256")
    L += brows("IDXB1", PERM)                          # 8-bit regs -> 8-bit array
    L.append("        .align 256")
    L += wrows("ACTSRC16", ACT)                        # copied to $1000
    L.append("        .align 256")
    L += brows("ACTSRC8", ACT)                         # copied to $1100
    L.append("")

    # ---- the code-as-weights bodies ---------------------------------------
    L.append("; 128 accumulates with the gather index in the operand byte.")
    L.append(".macro KCODE")
    for i in range(N):
        L.append("        adc z:$%02X" % (2 * PERM[i]))
    L.append(".endmacro")
    L.append("")

    L.append("; the same, sign separated: 64 adc, one sec, 64 sbc.  This is the")
    L.append("; shape a real row has -- one carry transition per ROW, not per MAC.")
    L.append(".macro KCODESGN")
    for i in range(N // 2):
        L.append("        adc z:$%02X" % (2 * PERM[i]))
    L.append("        sec")
    for i in range(N // 2, N):
        L.append("        sbc z:$%02X" % (2 * PERM[i]))
    L.append(".endmacro")
    L.append("")

    L.append("; 8-bit accumulator: the NES shape.  A block of 16 biased values")
    L.append("; cannot exceed 16*14 = 224 so no carry sets inside a block, and")
    L.append("; the block sum is folded into a 16-bit total every 16 elements.")
    L.append(".macro KCODE8")
    for i in range(N):
        L.append("        adc z:$%02X" % PERM[i])
        if i % 16 == 15:
            L.append("        FOLD8")
    L.append(".endmacro")
    L.append("")

    open(path, "w").write("\n".join(L) + "\n")

    m16 = lambda v: v & 0xFFFF
    exp = {
        "gather_sum": m16(sum(ACT)),
        "gather_sgn": m16(START + sum(ACT[PERM[i]] for i in range(N // 2))
                          - sum(ACT[PERM[i]] for i in range(N // 2, N))),
    }
    print(f"genkern: wrote {path}")
    print(f"  {N} elements, permutation seed 0x5A17, activations biased 0..14")
    for k, v in exp.items():
        print(f"  expect {k:12s} = ${v:04X} ({v})")
    return exp


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "rom/kern.inc")
